# Generated by Django 4.1.3 on 2022-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sait", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uni",
            name="description",
            field=models.TextField(max_length=75),
        ),
    ]
