# Generated by Django 4.1.3 on 2022-12-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sait", "0002_alter_uni_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="uni",
            name="number",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="uni",
            name="description",
            field=models.TextField(),
        ),
    ]
