# Generated by Django 4.1.3 on 2022-12-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sait", "0003_uni_number_alter_uni_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uni",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="uni",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="uni",
            name="ref",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="uni",
            name="title_ref",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="uni",
            name="tittle",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
