# Generated by Django 4.1.3 on 2022-12-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sait", "0004_alter_uni_description_alter_uni_image_alter_uni_ref_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uni",
            name="category",
            field=models.CharField(
                choices=[
                    ("MEDICINE", "MEDICINE"),
                    ("ENGINNER", "ENGINEER"),
                    ("MOUNTAIN", "MOUNTAIN"),
                    ("GOS", "GOS"),
                    ("TECHNOLOGIES", "TECHNOLOGIES"),
                    ("LANGUAGE", "LANGUAGE"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
